name: voila
channels:
  - conda-forge
dependencies:
  - python=3.10
  - ipywidgets
  - ipykernel
  - pandas
  - numpy
  - requests
  - scipy
  - matplotlib
  - ipyleaflet
  - pip
  - bokeh
  - bqplot
  - ipympl=0.9.2
  - jupyterlab-fasta
  - vega_datasets
  - ipyvolume
  - nodejs

  - pip:
      - voila==0.5.0
      - voila-topbar==0.1.1
