name: voila
channels:
  - conda-forge
dependencies:
  - python=3.10
  - ipykernel
  - ipywidgets=7.7.2
  - widgetsnbextension=3.6.1
  - pandas
  - numpy
  - requests
  - scipy
  - matplotlib
  - ipyleaflet
  - bokeh
  - bqplot
  - ipympl=0.9.2
  - vega_datasets
  - nodejs
  - pip
  - pip:
      - voila==0.5.0
      - voila-topbar==0.1.1

